version: "2.1"

services:

  python:
    image: approov/python-flask-shapes-demo
    build: ./docker
    restart: always
    env_file: .env.example
    environment:
      - FLASK_ENV=prod
    networks:
      - traefik
      - default
    command: "flask run -h 0.0.0.0"
    volumes:
      - "$PWD:/home/python/workspace"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=approov-python-flask-shapes-demo"
      - "traefik.docker.network=traefik"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host:python-flask-shapes-demo.pdm.approov.io"

networks:
  traefik:
    external: true
